FROM rust:1.85-slim

RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev curl && \
    curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh ./get-docker.sh && \
    rm -rf /var/lib/apt/lists/*

RUN rustup component add clippy rustfmt
RUN cargo install cargo-watch

ENV DOCKER_GROUP_ID=952

RUN groupadd -g ${DOCKER_GROUP_ID} docker-host-group; exit 0
RUN useradd -m rustdev || true
RUN usermod -aG ${DOCKER_GROUP_ID} rustdev

USER rustdev

WORKDIR /home/rustdev/app

CMD ["tail", "-f", "/dev/null"]
